# Services for Indevolt integration

charge:
  name: Charge Battery (real-time mode)
  description: Configures the battery to start charging based on known load settings.
  fields:
    device_id:
      name: Device
      description: The Indevolt device to charge
      required: true
      selector:
        device:
          integration: indevolt
    power:
      name: Maximum Charging Power
      description: The maximum Charging Power (Top-Up Power) in Watts.
      required: true
      selector:
        number:
          min: 100
          max: 1200
          unit_of_measurement: w

discharge:
  name: Discharge Battery (real-time mode)
  description: Configures the battery to start discharging to power your home.
  fields:
    device_id:
      name: Device
      description: The Indevolt device to discharge
      required: true
      selector:
        device:
          integration: indevolt
    power:
      name: Maximum Discharge Power
      description: The maximum Discharging Power (Max AC Output Power) in Watts.
      required: true
      selector:
        number:
          min: 0
          max: 800
          unit_of_measurement: w

stop:
  name: Stop Battery (real-time mode)
  description: Puts the battery into standby mode.
  fields:
    device_id:
      name: Device
      description: The Indevolt device to discharge
      required: true
      selector:
        device:
          integration: indevolt
